CREATE TABLE IF NOT EXISTS SYSTEM_ADMIN(
    Admin_ID INT PRIMARY KEY,
    Admin_Username VARCHAR(50) NOT NULL UNIQUE;
    Admin_Password VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCT(
    Product_ID INT PRIMARY KEY AUTO_INCREMENT,
    Product_Name VARCHAR(50) NOT NULL,
    Product_Price Decimal(10,2) NOT NULL,
    Product_Stock INT NOT NULL,
    Prodcut_Description Text,
    Product_Image BLOB
);

CREATE TABLE IF NOT EXISTS SUB_CATEGORY(
    Sub_Category_ID INT PRIMARY KEY AUTO_INCREMENT,
    Sub_Category_Name VARCHAR(50) NOT NULL,
    Product_ID INT,
    FOREIGN KEY (Product_ID) REFERENCES PRODUCT(Product_ID)
);

CREATE TABLE IF NOT EXISTS CATEGORY(
    Catergory_ID INT PRIMARY KEY AUTO_INCREMENT,
    Catergory_Name VARCHAR(50) NOT NULL,
    Sub_Category_ID INT,
    FOREIGN KEY (Sub_Category_ID) REFERENCES SUB_CATEGORY(Sub_Category_ID)
);

CREATE TABLE IF NOT EXISTS CLIENT(
    Client_ID INT PRIMARY KEY AUTO_INCREMENT,
    Client_Name VARCHAR(50) NOT NULL,
    Client_Mobile_Number VARCHAR(11) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS SALES(
    Sales_ID INT PRIMARY KEY AUTO_INCREMENT,
    Sales_Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Client_ID INT,
    Sales_Total_Amount DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (Client_ID) REFERENCES CLIENT(Client_ID)
);

CREATE TABLE IF NOT EXISTS SALES_DETAILS(
    Sales_Details_ID INT PRIMARY KEY AUTO_INCREMENT,
    Sales_ID INT,
    Product_ID INT,
    Sales_Quantity INT NOT NULL,
    Sales_Sub_Total DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (Sales_ID) REFERENCES SALE (Sales_ID),
    FOREIGN KEY (Product_ID) REFERENCES PRODUCT(Product_ID)
);


